#!/bin/sh
###############################################################################
#                                                                             #
# This file is managed by Puppet. While it can still be managed manually, it  #
# is definitely not recommended.                                              #
#                                                                             #
# Source: puppet-talk-production/files/cron/mongodb                           #
#                                                                             #
###############################################################################

# backup all mongodb data

date=`date +%u`
dir=/srv/backup/mongodb

mkdir -p $dir
cd $dir || exit 1

rm -rf dump-$date
mongodump -o dump-$date
